FROM bitnami/pgbouncer

ENV POSTGRESQL_HOST=containers-us-west-76.railway.app
ENV POSTGRESQL_USERNAME=postgres
ENV POSTGRESQL_PASSWORD=Bsnc6mdpHunKfxrKBVoY
ENV PGBOUNCER_POOL_MODE=transaction
ENV POSTGRESQL_PORT=7572
ENV PGBOUNCER_DATABASE=railway
ENV PGBOUNCER_SET_DATABASE_USER=yes
ENV PGBOUNCER_SET_DATABASE_PASSWORD=yes
