FROM bitnami/pgbouncer

ARG PGHOST
ARG PGDATABASE
ARG DATABASE_URL
ARG PGUSER
ARG PGPORT
ARG PGPASSWORD
ARG PORT

ENV POSTGRESQL_HOST=$PGHOST
ENV POSTGRESQL_USERNAME=$PGUSER
ENV PGBOUNCER_AUTH_USER=$PGUSER
ENV POSTGRESQL_PASSWORD=$PGPASSWORD
ENV POSTGRESQL_DATABASE=$PGDATABASE
ENV PGBOUNCER_POOL_MODE=transaction
ENV POSTGRESQL_PORT=$PGPORT
ENV PGBOUNCER_DATABASE=$PGDATABASE
ENV PGBOUNCER_EXTRA_FLAGS="--verbose"
ENV PGBOUNCER_AUTH_TYPE=trust
ENV PGBOUNCER_PORT=$PORT

EXPOSE $PORT
